# Generated by Django 6.0.2 on 2026-06-03 09:26

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_isreply_post_likes_post_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
