# Generated by Django 6.0.5 on 2026-06-19 06:51

import pgvector.django.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_embedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='posts_post_hnsw_idx', opclasses=['vector_ip_ops']),
        ),
    ]
