# Generated by Django 6.0.2 on 2026-06-03 09:26

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pulseuser',
            options={},
        ),
        migrations.AddField(
            model_name='pulseuser',
            name='user_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
