# Generated by Django 6.0.5 on 2026-06-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_pulseuser_options_pulseuser_user_embedding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pulseuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='pulseuser',
            name='user_embedding',
        ),
    ]
